### ISSUE TITLE
Artnet data not recieved

### ISSUE THREAD

**Issue by lightman210567** [open-stage/blender-dmx#39]
When i enable artnet input (after i have setup a artnet source), the plugin menu hangs on "Waiting for data". If it actually connects (which is rare), no changes are applied to the fixture - for example changing the pan channel does not pan the fixture.

**Comment by vanous** [comment]
This is a setup/user error. It happens because you already have another program listening for Art-Net data. Make sure to close it or restart your computer. It could be the Art-Net sender program too or another Blender instance. One way to get around this is to start the Blender (DMX) Art-Net receiving first.

**Comment by lightman210567** [comment]
I will try this, thank you for your advice
