### ISSUE TITLE
Error add fixtures

### ISSUE THREAD

**Issue by frphilippe** [open-stage/blender-dmx#44]
Good morning,
When I try to add a fixture on the scene an error message appears.
This message concerns an error in the python script and apparently an unrecognized path.
when I hover over the fixtures to choose a popup tells me (undocumented operator).
I work with linux mint 20.1 and blender 2.82a. The same problem occurs with Blender 3
I am attaching a screenshot.
![Capture d’écran du 2023-07-19 10-49-50](https://github.com/open-stage/blender-dmx/assets/48242265/fe4ac8c4-2e07-407a-90f2-b328943abdd6)

**Comment by vanous** [comment]
Sorry for late reply. Most likely Blender 2.x will not work anymore (due to old python). I just tested the [installation instructions](https://github.com/open-stage/blender-dmx#download--install) (for the rolling release) with Blender 3.6.2 on Debian and all is working well. If the issue persists, try to ask for help in [discord](https://discord.com/invite/FQVVyc45T9).
