### ISSUE TITLE
please attach sample project file

### ISSUE THREAD

**Issue by ScobbyDoo** [open-stage/blender-dmx#71]
sample project file will be helpful to test output at initial stage

**Comment by vanous** [comment]
This is a good idea and also a plan. For this, we will use an MVR file as it can be re-parsed over time as capabilities are being added to Blender-DMX. An MVR file can also easily be loaded into DMX consoles. If you like to provide such a file, feel free to discuss this in the Discord forum.

**Comment by ScobbyDoo** [comment]
Any progress?

**Comment by vanous** [comment]
Hey @ScobbyDoo ,

thanks for asking! Nobody offered any MVR as a sample project as far as i am aware and i have no plan (no time) at this moment to prepare one. If you do, feel free to discuss this in Discord.

I think this discussion is better to be done there then here in the issue tracker, let me close this issue here, any further readers, please follow up through Discord. Thank you!
